# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29aaf24662236dde6637ed65ecc0c5f4f6130de7c965403209a51651ad4ff2e05770731678b63a5359be790a66bc4e4ebb27a206fb7007ca34b07dd4a281c578

test:
  secret_key_base: 47820d6d0a5988e751f3b326f5f5267c7039b55d00a26cae1484544d5ab69e50c326a99958e27cab56e2e94e796b92d8255d1c20ffc7ce50e6e0d00993ef9715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
